development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
# production environment handled by heroku's database.yml autogenerator
# http://devcenter.heroku.com/articles/database#using_the__environment_variable_rails